CREATE TABLE "GCG_6825_SETTINGS" (
 "REC_ID" INTEGER,
 "REMOTEHOST" CHAR(50),
 "REMOTEUSER" CHAR(50),
 "REMOTEPASSWORD" CHAR(50),
 "REMOTEPORT" CHAR(50),
 "REMOTEPATH" CHAR(50),
 "DATE_LAST_CHG" CHAR(8),
 "TIME_LAST_CHG" CHAR(8),
 "DEL_FILE" CHAR(1),
 "PUSH_FILE" CHAR(1),
 "DAYS" INTEGER );